return [[
===RAW URLS(FILES)===

Scripts_1: https://raw.githubusercontent.com/ssakeen679-alt/agent/refs/heads/main/SCRIPT_ARCHIVE/Scripts/Scripts_1.legacy.luau

LocalScripts_1: https://raw.githubusercontent.com/ssakeen679-alt/agent/refs/heads/main/SCRIPT_ARCHIVE/LocalScripts/LocalScripts_1.legacy.luau

LocalScripts_2: https://raw.githubusercontent.com/ssakeen679-alt/agent/refs/heads/main/SCRIPT_ARCHIVE/LocalScripts/LocalScripts_2.legacy.luau

ModuleScripts_1: https://raw.githubusercontent.com/ssakeen679-alt/agent/refs/heads/main/SCRIPT_ARCHIVE/ModuleScripts/ModuleScripts_1.legacy.luau

ModuleScripts_2: https://raw.githubusercontent.com/ssakeen679-alt/agent/refs/heads/main/SCRIPT_ARCHIVE/ModuleScripts/ModuleScripts_2.legacy.luau

]]